// Shared between the frontend (src/) and the API (api/src/) — kept as a single
// source of truth for what a flagged item looks like, since both sides need to
// agree on the shape without a build step gluing them together.

export type ItemCategory =
  | "ICM_ISSUE" // formerly "DCI" — ICM STA verification issue (Issues to Correct)
  | "BM_PRN_MISSED"
  | "HRST_EXPIRING"
  | "CHART_MISSED"
  | "APPOINTMENT"
  | "FMLA";

export type ItemSeverity = "red" | "amber" | "info";

export type ItemStatus = "pending" | "reviewed";

// Categories where "reviewed" only dismisses the item until the underlying
// condition changes (it will reappear if still unresolved on the next refresh).
// Everything else is a one-time acknowledgement that dismisses permanently.
// See docs/program-portal-architecture.md §5.
export const REAPPEARING_CATEGORIES: ReadonlySet<ItemCategory> = new Set([
  "BM_PRN_MISSED",
  "HRST_EXPIRING",
  "CHART_MISSED",
]);

export interface DailyItem {
  /** Stable id derived from psEmail + category + a key unique to the underlying issue. */
  id: string;
  psEmail: string;
  psName: string;
  category: ItemCategory;
  severity: ItemSeverity;
  individual: string;
  description: string;
  /** ISO date (yyyy-mm-dd) the item was generated by the most recent refresh. */
  sourceDate: string;
  /** ISO date the item first appeared, unchanged across refreshes while unresolved. */
  firstSeenDate: string;
  status: ItemStatus;
  reviewedBy: string | null;
  reviewedAt: string | null;
}

export interface ItemsResponse {
  items: DailyItem[];
  generatedAt: string;
}

export const CATEGORY_LABELS: Record<ItemCategory, string> = {
  ICM_ISSUE: "ICM STA Issues",
  BM_PRN_MISSED: "BM / PRN Protocol",
  HRST_EXPIRING: "HRST Expirations",
  CHART_MISSED: "Missed Charts",
  APPOINTMENT: "Appointments",
  FMLA: "FMLA / Leave Status",
};
